/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	k8scrdiov1alpha1 "github.com/kubernetes-cluster-monitor/controller/pkg/apis/k8s.crd.io/v1alpha1"
	versioned "github.com/kubernetes-cluster-monitor/controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kubernetes-cluster-monitor/controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kubernetes-cluster-monitor/controller/pkg/client/listers/k8s.crd.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PolicyDefinitionInformer provides access to a shared informer and lister for
// PolicyDefinitions.
type PolicyDefinitionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PolicyDefinitionLister
}

type policyDefinitionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPolicyDefinitionInformer constructs a new informer for PolicyDefinition type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPolicyDefinitionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPolicyDefinitionInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPolicyDefinitionInformer constructs a new informer for PolicyDefinition type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPolicyDefinitionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.K8sV1alpha1().PolicyDefinitions(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.K8sV1alpha1().PolicyDefinitions(namespace).Watch(context.TODO(), options)
			},
		},
		&k8scrdiov1alpha1.PolicyDefinition{},
		resyncPeriod,
		indexers,
	)
}

func (f *policyDefinitionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPolicyDefinitionInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *policyDefinitionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&k8scrdiov1alpha1.PolicyDefinition{}, f.defaultInformer)
}

func (f *policyDefinitionInformer) Lister() v1alpha1.PolicyDefinitionLister {
	return v1alpha1.NewPolicyDefinitionLister(f.Informer().GetIndexer())
}
