/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/cisco/CustomResource/src/pkg/apis/myproject/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeReceivers implements ReceiverInterface
type FakeReceivers struct {
	Fake *FakeSampleprojectV1alpha1
	ns   string
}

var receiversResource = schema.GroupVersionResource{Group: "sampleproject.io", Version: "v1alpha1", Resource: "receivers"}

var receiversKind = schema.GroupVersionKind{Group: "sampleproject.io", Version: "v1alpha1", Kind: "Receiver"}

// Get takes name of the receiver, and returns the corresponding receiver object, and an error if there is any.
func (c *FakeReceivers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Receiver, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(receiversResource, c.ns, name), &v1alpha1.Receiver{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Receiver), err
}

// List takes label and field selectors, and returns the list of Receivers that match those selectors.
func (c *FakeReceivers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ReceiverList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(receiversResource, receiversKind, c.ns, opts), &v1alpha1.ReceiverList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ReceiverList{ListMeta: obj.(*v1alpha1.ReceiverList).ListMeta}
	for _, item := range obj.(*v1alpha1.ReceiverList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested receivers.
func (c *FakeReceivers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(receiversResource, c.ns, opts))

}

// Create takes the representation of a receiver and creates it.  Returns the server's representation of the receiver, and an error, if there is any.
func (c *FakeReceivers) Create(ctx context.Context, receiver *v1alpha1.Receiver, opts v1.CreateOptions) (result *v1alpha1.Receiver, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(receiversResource, c.ns, receiver), &v1alpha1.Receiver{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Receiver), err
}

// Update takes the representation of a receiver and updates it. Returns the server's representation of the receiver, and an error, if there is any.
func (c *FakeReceivers) Update(ctx context.Context, receiver *v1alpha1.Receiver, opts v1.UpdateOptions) (result *v1alpha1.Receiver, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(receiversResource, c.ns, receiver), &v1alpha1.Receiver{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Receiver), err
}

// Delete takes name of the receiver and deletes it. Returns an error if one occurs.
func (c *FakeReceivers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(receiversResource, c.ns, name), &v1alpha1.Receiver{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeReceivers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(receiversResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ReceiverList{})
	return err
}

// Patch applies the patch and returns the patched receiver.
func (c *FakeReceivers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Receiver, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(receiversResource, c.ns, name, pt, data, subresources...), &v1alpha1.Receiver{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Receiver), err
}
